###############################################################
#
# Purpose: Makefile for "assist program"
# Author.: Zihong Zheng (zzhonzi@gmail.com)
# Version: 1.0
# License: 
#
###############################################################


all:
	javac *.java
	g++ starter.cpp -o starter -Wall

clean:
	rm -rf *.class
	rm -rf starter
	
