###############################################################
#
# Purpose: Makefile for "JClient"
# Author.: Zihong Zheng
# Version: 0.1
# License: 
#
###############################################################


all:
	javac *.java -cp jmfapi-1.0-SNAPSHOT.jar

run:
	sudo java -cp .:jmfapi-1.0-SNAPSHOT.jar JClient 101 102
		
clean:
	rm -rf *.class