###############################################################
#
# Purpose: Makefile for "JClient", actually just for clean
# Author.: Zihong Zheng
# Version: 0.1
# License: 
#
###############################################################


clean:
	rm -rf *.class
